config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :products
  resources :leads
  resources :contacts
  resources :accounts

  root 'home#index'
  get "list_accounts" => "accounts#list_accounts", as: "list_accounts"
  get "list_contacts" => "accounts#list_contacts", as: "list_contacts"
  get "name" => "contacts#name", as: "name"
  get "list_products" => "categories#list_products", as: "list_products"

end

app/models/account.rb
class Account < ActiveRecord::Base
   include PgSearch
   pg_search_scope :search,
                  :against => :name,
                  :using => {
                    :tsearch => {:prefix => true}
                  }
  #  multisearchable :against => [:name]
   has_many :contacts
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  include PgSearch
  pg_search_scope :search,
                 :against => :name,
                 :using => {
                   :tsearch => {:prefix => true}
                 }
  # pg_search_scope :search_by_name, :against => :name
  # multisearchable :against => [:account_name]
  belongs_to :account
  delegate :name, :to => :account, :prefix => true
end

app/models/lead.rb
class Lead < ActiveRecord::Base

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
def index
    @account = Account.all
end

def new
    @account = Account.new
end

def show
end

def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to @account, notice: "Your post was created successfully."
    else
      render :new
    end
end

def list_accounts
  @accounts =  Account.search(params[:value])
  @values = []
  if @accounts.present?
    @accounts.each do |account|
      @values.push(account.as_json(include: { contacts: { only: [:id, :name] }}, only: [:id, :name]))
    end
  end
  render json: @values
end

def list_contacts
  @contacts =  Contact.search(params[:value])
  @values = []
  if @contacts.present?
    @contacts.each do |contact|
      @values.push(contact.as_json(include: { account: { only: [:name] }}, only: [:id, :name]))
    end
  end
  render json: @values
end

# def list_contacts
#   @records =  PgSearch.multisearch(params[:value])
#   render json: @records
# end

# def list_account_contacts
#   @records =  PgSearch.multisearch(params[:value])
#   render json: @records
# end

  private

  def account_params
    params.require(:account).permit(:name, :location)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end


  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def list_products
    @category = Category.find(params[:value])
    render json: @category.products
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
def index
    @contact = Contact.all
end

def new
    @contact = Contact.new
end

def show
end

def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to @contact, notice: "Your contact was created successfully."
    else
      render :new
    end
end

def name
  @contact = Contact.find(params[:value])
  @names = []
  @names.push(@contact.as_json(include: { account: { only: [:name] }}, only: [:name]))
  render json:  @names
end

  private

  def contact_params
    params.require(:contact).permit(:account_id, :name, :contact_number)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
    def new
        @pg_search_documents = PgSearch.multisearch(params[:query])
        #@q = Account.ransack(params[:q])
        #@accounts = @q.result
        #@accounts = Account.where(name: params["name"]) if params["name"].present?
        #@contacts = Contact.where(name: params["name"]) if params["name"].present?
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= form_for @account do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_for @contact do |f| %>
  <div class="field">
    <%= f.label :account_id %><br />
    <%= f.collection_select :account_id, Account.order(:name), :id, :name, include_blank: true %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.text_field :contact_number %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/home/index.html.erb
<html>
  <head>
    <title>
    </title>
  </head>
  <body>
    <div class="container">
      <div id="account_field">
        <div class="row">
          <div class="col-md-2">
            <div class="form-group">
              <%= text_field_tag "account_name", "", id: "account_name", class: "form-control", placeholder: "Account Name" %>
            </div>
          </div>
          <div class="col-md-2">
            <div class="form-group">
              <%= text_field_tag "contact_name", "", id: "contact_name", class: "form-control", placeholder: "Contact Name" %>
            </div>
          </div>
          <div class="col-md-2">
            <span><button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">Search Account/Contact Name</button>
          </div>
          <div class="col-md-2">
            <div class="form-group">
                <%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name"), {:class => "form-control", prompt: "Select Category"} %>
            </div>
          </div>
          <div class="col-md-2">
            <div class="form-group" id="product">
                <select id="product" name= "product_id", class="form-control"><option>Select Product</option></select>
            </div>
          </div>
      </div>
        <!-- Trigger the modal with a button -->


        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Account Name</h4>
              </div>
              <div class="modal-body">
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <input id="acc_search_value" type="text" class="form-control" placeholder="Account Name"/>
                    </div>
                    <div class="form-group">
                      <input id="cont_search_value" type="text" class="form-control" placeholder="Contact Name" />
                    </div>
                    <div class="form-group">
                      <button type="button" id="acc_search" class="btn btn-success">Search Account</button>
                    </div>
                    <div class="form-group">
                      <div id="search-results">
                        <!-- <ul id="lists"></ul> -->
                      </div>
                    </div>
                  </div>
                  <!-- <div class="col-md-6">
                      <input id="cont_search_value" type="text"/><button type="button" id="cont_search">Search Contact</button>
                      <div id="search-results">
                        <ul id="lists"></ul>
                      </div>
                  </div> -->
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

      </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leads/new.html.erb
<%= form_tag new_lead_path, method: :get, id: "search-form" do %>
<%= text_field_tag :query, params[:query] %>
<%= submit_tag "Search", name: nil %>
<% end %>


<% @pg_search_documents.each do |pg_search_document| %>
    <li><%= link_to pg_search_document.searchable.name, "../#{(pg_search_document.searchable.class).to_s.downcase!.pluralize}/#{pg_search_document.searchable.id}" %></li>
  <% end %>
  

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>